net_interface = "ens18" # Put here the network interface you want to use.

[devices]

    [devices."C0:95:6D:5B:A6:D1"]    # A shared bonjour device
    description = "Lounge"
    origin_pool = 40               # Tag of the VLAN the device is in
    shared_pools = [0, 25, 30]      # Tags of the VLANs which can use this device

#    [devices."AA:00:CC:00:EE:00"]
#    description = "Test Spotify Air"
#    origin_pool = 1078
#    shared_pools = [1234, 1547, 2483]
#
#    [devices."AA:11:CC:11:EE:11"]
#    description = "Test Spotify Air"
#    origin_pool = 1547
#    shared_pools = [1078, 2483, 3133]
